### ISSUE TITLE
customers changeset

### ISSUE THREAD

**Issue by peillis** [peillis/siwapp#15]

**Comment by ale1311sv** [comment]
Enrique, i've tested the customer changeset we discussed before and it seems to works properly. 

The Siwapp.Schema.Customer.changeset takes a Customer Struct as first argument and the attributes you want to change or create as the second argument. We discussed before the case when a Customer Struct is not empty and the attributes are an empty map like Customer.Changeset(%Customer{name: "whatever"}, %{}). It says that either :name or :identification are required because we are saying the change is an empty map without a name or an identification field.

In other case, imagine that you want to change the name of a customer. You must validate before update doing Customer.changeset(%Customer{name: "whatever"}, %{name: "whenever}).  I've tested and this would correctly change the name from whatever to whenever. 
I've tested also the update_customer function and also works. This function updates a customer given an id and introduces the new values in the database.
